### ISSUE TITLE
Any Hope of 64-bit Support?

### ISSUE THREAD

**Issue by bwalls** [Jean-Daniel/Spark#10]
I'm assuming not, but with macOS 10.15 Catalina now out, it's going to be a common question.

**Comment by Jean-Daniel** [comment]
Hello,

You can download the last version at https://www.shadowlab.org/softwares/Spark/Spark.zip <https://www.shadowlab.org/softwares/Spark/Spark.zip>
It does not supports Music yet though.

Regards
Jean-Daniel Dupas

**Comment by mattavery** [comment]
Thank you!

**Comment by Jean-Daniel** [comment]
Hello,

Just in case, I just did push on the web site an updated version that support Music (instead of iTunes) and is properly signed (so should not display warning at first launch).

Regards
